### ISSUE TITLE
ios16.4 crash because "Type 'Animation?' has no member 'bouncy'"

### ISSUE THREAD

**Issue by no13bus** [notsobigcompany/BigUIPaging#4]

**Comment by phillipcaudell** [comment]
Could you please provide steps to reproduce?

**Comment by no13bus** [comment]
sorry, I make the mistake, after I update the xcode to xcode15, it is gone.
By the way, actually I want to do this:
after user swipe one page, then I do want to delete it, I do not want to user to see it any more. Is it possible for me to use this library?

**Comment by phillipcaudell** [comment]
Yes, you would need to update your underlying model in the next or previous closure. Good luck!
